version: 2

sources:
  - name: MANISH_AIW24
    description: "Class test data"
    database: MANISH_AIW24
    schema: CLASS_TEST
    tables:
      - name: CUSTOMERS
        description: "This is the Customer Table info"
      - name: ORDERS
        description: "This is orders table info"
      - name: PRODUCT
        description: "This is a product table info"

# models:
#   # Define your models here...
